### ISSUE TITLE
Need update for the latest version on npm

### ISSUE THREAD

**Issue by leonardodalinky** [chaosmail/onnx-proto#5]
Hi! I'm working on an onnx-related project and found out that the `onnx-proto` library on `npm` is outdated. I think it's dumb to rebuild from the source for my work, so I wonder if u could do this for me?

The latest version for onnx is 1.10 and the `ir_version` comes to `8`, while the current onnx version on `npm` is 1.5 and its `ir_version` remains `5`.

Thanks if u could publish a newer version!😀

**Comment by chaosmail** [comment]
Updated to onnx/onnx `v1.10.2` - I used the IR version `8` as new major version for `onnx-proto`. I fixed a few things in the project structure, so you can configure the onnx version directly in the `package.json` file.

**Comment by leonardodalinky** [comment]
Thank you for all the help!!! :)
